[task-base]
cpuNum = 4
redisAddr = "localhost:6379"
redisPassword = ""
rpcAddress = "tcp@localhost:6923"
pushChan = 2
pushChanSize = 50
kafakSeverAddress = "localhost:9092"
consumerGroup = "gochat_group"
consumerTopic = "gochat_queue"
consumerPort = ":8081"
producerPort = ":8082"
