[task-base]
cpuNum = 4
redisAddr = "localhost:6379"
redisPassword = ""
rpcAddress = "tcp@localhost:6923"
pushChan = 2
pushChanSize = 50
kafkaServerAddress = "localhost:9093"
consumerGroup = "gochat_group"
consumerTopic = "gochat_queue"
